name = "topology"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
build_base_image = "golang:1.18-buster"
# module_path = "github.com/your/module/name"
# exec_pkg = "."

[builders."exec:go"]
enabled = true
exec_pkg = "."
# go_version = "1.18"
# module_path = "github.com/your/module/name"

[runners."local:exec"]
enabled = true

[runners."local:docker"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name= "subnets"
instances = { min = 95, max = 100, default = 100 }
    [testcase.params]
    clusters = { type = "string", desc = "path to cluster yaml", default = ".clusters.yaml" }
    subnets = { type = "int", desc = "number of subents to use", default = 128 }
    max_peers = { type = "int", desc = "maximum number of connected peers", default = 25 }
    t_latency = { type = "int", desc = "network latency between nodes", unit = "ms", default=5 }
    t_latency_max = { type = "int", desc = "if supplied, latency is between t_latency and t_latency_max", unit = "ms", default=50 }
    validation_latency = { type = "int", desc = "maximum value for validation latency", unit = "ms", default = 5 }

[[testcases]]
name= "groups"
instances = { min = 95, max = 100, default = 100 }
    clusters = { type = "string", desc = "path to cluster yaml", default = ".clusters.yaml" }
#     subnets = { type = "int", desc = "number of subents to use", default = 128 }
    max_peers = { type = "int", desc = "maximum number of connected peers", default = 25 }
    t_latency = { type = "int", desc = "network latency between nodes", unit = "ms", default=5 }
    t_latency_max = { type = "int", desc = "if supplied, latency is between t_latency and t_latency_max", unit = "ms", default=50 }
    validation_latency = { type = "int", desc = "maximum value for validation latency", unit = "ms", default = 5 }
